# Generated by Django 3.0.6 on 2020-06-05 20:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField(default=datetime.time(0, 0))),
                ('hora_final', models.TimeField(null=True)),
            ],
        ),
    ]
