# Generated by Django 3.0.6 on 2020-06-05 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teatro', '0001_initial'),
        ('sala', '0001_initial'),
        ('persona', '0001_initial'),
        ('funcion', '0001_initial'),
        ('pelicula', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcion',
            name='empleado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='persona.Empleado'),
        ),
        migrations.AddField(
            model_name='funcion',
            name='pelicula',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pelicula.Pelicula'),
        ),
        migrations.AddField(
            model_name='funcion',
            name='sala',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sala.Sala'),
        ),
        migrations.AddField(
            model_name='funcion',
            name='teatro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teatro.Teatro'),
        ),
    ]
