# Generated by Django 3.0.6 on 2020-06-05 20:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teatro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, 'El número de la sala debe ser mayor 1')])),
                ('cap_general', models.PositiveSmallIntegerField()),
                ('cap_primera_clase', models.PositiveSmallIntegerField()),
                ('cap_discapacitados', models.PositiveSmallIntegerField()),
                ('tipo_formato', models.CharField(choices=[('2d', 'Sala 2D'), ('3d', 'Sala 3D'), ('4d', 'Sala 4D'), ('mega', 'Megasala'), ('vip', 'Sala VIP')], default='2d', max_length=4)),
                ('teatro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teatro.Teatro')),
            ],
            options={
                'unique_together': {('numero', 'teatro')},
            },
        ),
        migrations.CreateModel(
            name='Silla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_x', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('pos_y', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('tipo', models.CharField(max_length=20)),
                ('nombre', models.CharField(default='', max_length=10)),
                ('sala', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sala.Sala')),
            ],
        ),
    ]
