# Generated by Django 3.0.6 on 2020-05-30 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sala', '0001_initial'),
        ('funcion', '0002_auto_20200519_0302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_venta', models.DateTimeField(auto_now_add=True)),
                ('funcion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='funcion.Funcion')),
                ('silla', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sala.Silla')),
            ],
        ),
    ]
