# Generated by Django 3.0.6 on 2020-06-05 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sala', '0001_initial'),
        ('boleta', '0001_initial'),
        ('funcion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='funcion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='funcion.Funcion'),
        ),
        migrations.AddField(
            model_name='boleta',
            name='silla',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sala.Silla'),
        ),
    ]
