# Generated by Django 3.0.6 on 2020-06-05 20:57

import datetime
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_cartelera', models.BooleanField(default=False)),
                ('es_estreno', models.BooleanField(default=False)),
                ('nombre', models.CharField(max_length=25)),
                ('duracion', models.TimeField(default=datetime.time(0, 0))),
                ('sinopsis', models.CharField(default='Sinopsis pendiente', max_length=300)),
                ('genero', models.CharField(choices=[('acc', 'Acción'), ('dr', 'Drama'), ('com', 'Comedia'), ('ter', 'Terror'), ('th', 'Thriller'), ('inf', 'Infantil')], max_length=5)),
                ('pais', django_countries.fields.CountryField(max_length=15)),
                ('imagen', models.ImageField(default='pelicula/default.png', upload_to='pelicula/')),
                ('trailer', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
