# Generated by Django 3.0.6 on 2020-05-30 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelicula', '0002_pelicula_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='en_cartelera',
            field=models.BooleanField(default=False),
        ),
    ]
