# Generated by Django 3.0.6 on 2020-06-01 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelicula', '0003_pelicula_en_cartelera'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='es_estreno',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='imagen',
            field=models.ImageField(default='img/pelicula/default.png', upload_to='img/pelicula/'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='sinopsis',
            field=models.CharField(default='Sinopsis pendiente', max_length=300),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='trailer',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='genero',
            field=models.CharField(choices=[('acc', 'Acción'), ('dr', 'Drama'), ('com', 'Comedia'), ('ter', 'Terror'), ('th', 'Thriller'), ('inf', 'Infantil')], max_length=5),
        ),
    ]
